name: Workflow Overview

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  my_self_hosted_job:
    name: My self-hosted job
    runs-on: self-hosted
    steps:
      - name: Step in a self-hosted runner
        id: selfHostedId
        shell: cmd
        run: |
          echo this is a multiline comment
          echo and this job has been executed from my self-hosted runner
  a_simple_job:
    name: My simple job name
    runs-on: ubuntu-latest
    steps:
      - name: Name of my step
        id: stepId
        run: echo "This is the first step from the first job"
      - name: Step with another shell
        id: shellStep
        shell: python
        run: print("This step is using the python shell")
